- name: main
  hosts: admin:webservers
  roles: 
        - { role: basic, tags: basic }

- name: webserver
  hosts: webservers
  roles:
        - { role: mysql, tags: mysql }
        - { role: nginx, tags: nginx }
        - { role: php-fpm, tags: php-fpm }
        - { role: wordpress, tags: wordpress }


- name: server
  hosts: server
  roles: 
    - { role: zabbix, tags: zabbix } 