---


- name: Install mysql packages
  apt: 
    name: 
    - mysql-server
    - python3-mysqldb
    state: present

- name: Create wordpress database
  mysql_db: name={{ wp_db_name }} state=present #will take variable from group_vars-webserver1 file #modules in ansible website #creating a database
   #use : if not on the same line with variable if it is then use = sign

- name: Create wordpress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present 
  #creating user to access a database #privileges should have access to database 
  #.* means to all tables on that database 
  #:ALL means all actions
  #where is the our database in localhost
  

- name: Start mysql service
  service:
    name: mysql
    state: started
    enabled: yes #make sure it will strated after reboot 
    

